<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.7.0';
$moduleRevision = '65fd52c7685cc1c81e85448fe776f55887c6ae7c';
$moduleWikiUrl = '';